package blend

import _ "embed"

//go:embed testdata/oracle_stored_layout.json
var oracleStoredLayout []byte

//go:embed testdata/v1_09_comet_vectors.json
var cometValuationVectors []byte

// OracleStoredLayoutFixture returns the raw v2 oracle stored-layout fixture
// (the on-ledger oracle storage snapshot used as ground truth for fold tests).
//
// The bytes are embedded into the module at build time, so downstream consumers
// can read this fixture through the pinned module rather than reaching into a
// sibling checkout by filesystem path. Callers must not mutate the returned slice.
func OracleStoredLayoutFixture() []byte { return oracleStoredLayout }

// CometValuationVectorsFixture returns the raw V1-09 neutral Comet valuation
// vectors (testdata/v1_09_comet_vectors.json): shares -> LP tokens -> floor
// component decomposition -> two-legged USD, including the absent-not-zero and
// zero-denominator cases. Expected values are generated by a standalone integer
// oracle that imports neither production engine (see the file's provenance
// note); Go, relay, and relay.rs consumers must agree with them exactly —
// production output must never be written back into this file.
//
// Embedded at build time like OracleStoredLayoutFixture. Callers must not
// mutate the returned slice.
func CometValuationVectorsFixture() []byte { return cometValuationVectors }
